<?php

use Carbon\Carbon;

if (!function_exists('formatTanggal')) {
    function formatTanggal($tanggal = null, $format = 'l, j F Y')
    {
        $parsedDate = Carbon::parse($tanggal)->locale('id')->settings(['formatFunction' => 'translatedFormat']);
        return $parsedDate->format($format);
    }
}

if (!function_exists('formatRupiah')) {
    function formatRupiah($amount)
    {
        return 'Rp ' . number_format($amount, 0, ',', '.');
    }
}

if (!function_exists('kotaIndonesia')) {
    function kotaIndonesia($amount)
    {
        return [
            'KAB. ACEH BARAT',
            'KAB. ACEH BARAT DAYA',
            'KAB. ACEH BESAR',
            'KAB. ACEH JAYA',
            'KAB. ACEH SELATAN',
            'KAB. ACEH SINGKIL',
            'KAB. ACEH TAMIANG',
            'KAB. ACEH TENGAH',
            'KAB. ACEH TENGGARA',
            'KAB. ACEH TIMUR',
            'KAB. ACEH UTARA',
            'KAB. BENER MERIAH',
            'KAB. BIREUEN',
            'KAB. GAYO LUES',
            'KAB. NAGAN RAYA',
            'KAB. PIDIE',
            'KAB. PIDIE JAYA',
            'KAB. SIMEULUE',
            'BANDA ACEH',
            'LANGSA',
            'LHOKSEUMAWE',
            'SABANG',
            'SUBULUSSALAM',
            'KAB. BADUNG',
            'KAB. BANGIL',
            'KAB. BULELENG',
            'KAB. GIANYAR',
            'KAB. JEMBRANA',
            'KAB. KARANGASEM',
            'KAB. KLUNGKUNG',
            'KAB. TABANAN',
            'DENPASAR',
            'KAB. LEBAK',
            'KAB. PANDEGLANG',
            'KAB. SERANG',
            'KAB. TANGERANG',
            'CILEGON',
            'SERANG',
            'TANGERANG',
            'TANGERANG SELATAN',
            'KAB. BENGKULU SELATAN',
            'KAB. BENGKULU TENGAH',
            'KAB. BENGKULU UTARA',
            'KAB. KAUR',
            'KAB. KAPAHIANG',
            'KAB. LEBONG',
            'KAB. MUKOMUKO',
            'KAB. REJANG LEBONG',
            'KAB. SELUMA',
            'BENGKULU',
            'KAB. BANTUL',
            'KAB. GUNUNG KIDUL',
            'KAB. KULON PROGO',
            'KAB. SLEMAN',
            'YOGYAKARTA',
            'KAB. KEPULAUAN SERIBU',
            'JAKARTA BARAT',
            'JAKARTA PUSAT',
            'JAKARTA SELATAN',
            'JAKARTA TIMUR',
            'JAKARTA UTARA',
            'KAB. BOALEMO',
            'KAB. BONE BOLANGO',
            'KAB. GORONTALO',
            'KAB. GORONTALO UTARA',
            'KAB. PAHUWATO',
            'GORONTALO',
            'KAB. BATANGHARI',
            'KAB. BUNGO',
            'KAB. KERINCI',
            'KAB. MERANGIN',
            'KAB. MUARO JAMBI',
            'KAB. SAROLANGUN',
            'KAB. TANJUNG JABUNG BARAT',
            'KAB. TANJUNG JABUNG TIMUR',
            'KAB. TEBO',
            'JAMBI',
            'SUNGAI PENUH',
            'KAB. BANDUNG',
            'KAB. BANDUNG BARAT',
            'KAB. BEKASI',
            'KAB. BOGOR',
            'KAB. CIAMIS',
            'KAB. CIANJUR',
            'KAB. CIREBON',
            'KAB. GARUT',
            'KAB. INDRAMAYU',
            'KAB. KARAWANG',
            'KAB. KUNINGAN',
            'KAB. MAJALENGKA',
            'KAB. PANGANDARAN',
            'KAB. PURWAKARTA',
            'KAB. SUBANG',
            'KAB. SUKABUMI',
            'KAB. SUMEDANG',
            'KAB. TASIKMALAYA',
            'BANDUNG',
            'BANJAR',
            'BEKASI',
            'BOGOR',
            'CIMAHI',
            'CIREBON',
            'DEPOK',
            'SUKABUMI',
            'TASIKMALAYA',
            'KAB. BANJARNEGARA',
            'KAB. BANYUMAS',
            'KAB. BATANG',
            'KAB. BLORA',
            'KAB. BOYOLALI',
            'KAB. BREBES',
            'KAB. CILACAP',
            'KAB. DEMAK',
            'KAB. GROBOGAN',
            'KAB. JEPARA',
            'KAB. KARANGANYAR',
            'KAB. KEBUMEN',
            'KAB. KENDAL',
            'KAB. KLATEN',
            'KAB. KUDUS',
            'KAB. MAGELANG',
            'KAB. PATI',
            'KAB. PEKALONGAN',
            'KAB. PEMALANG',
            'KAB. PURBALINGGA',
            'KAB. PURWOREJO',
            'KAB. REMBANG',
            'KAB. SEMARANG',
            'KAB. SRAGEN',
            'KAB. SUKOHARJO',
            'KAB. TEGAL',
            'KAB. TEMANGGUNG',
            'KAB. WONOGIRI',
            'KAB. WONOSOBO',
            'MAGELANG',
            'PEKALONGAN',
            'SALATIGA',
            'SEMARANG',
            'SURAKARTA',
            'TEGAL',
            'KAB. BANGKALAN',
            'KAB. BANYUWANGI',
            'KAB. BLITAR',
            'KAB. BOJONEGORO',
            'KAB. BONDOWOSO',
            'KAB. GRESIK',
            'KAB. JEMBER',
            'KAB. JOMBANG',
            'KAB. KEDIRI',
            'KAB. LAMONGAN',
            'KAB. LUMAJANG',
            'KAB. MADIUN',
            'KAB. MAGETAN',
            'KAB. MALANG',
            'KAB. MOJOKERTO',
            'KAB. NGANJUK',
            'KAB. NGAWI',
            'KAB. PACITAN',
            'KAB. PAMEKASAN',
            'KAB. PASURUAN',
            'KAB. PONOROGO',
            'KAB. PROBOLINGGO',
            'KAB. SAMPANG',
            'KAB. SIDOARJO',
            'KAB. SITUBONDO',
            'KAB. SUMENEP',
            'KAB. TRENGGALEK',
            'KAB. TUBAN',
            'KAB. TULUNGAGUNG',
            'BATU',
            'BLITAR',
            'KEDIRI',
            'MADIUN',
            'MALANG',
            'MOJOKERTO',
            'PASURUAN',
            'PROBOLINGGO',
            'SURABAYA',
            'KAB. BENGKAYANG',
            'KAB. KAPUAS HULU',
            'KAB. KAYONG UTARA',
            'KAB. KETAPANG',
            'KAB. KUBU RAYA',
            'KAB. LANDAK',
            'KAB. MELAWI',
            'KAB. PONTIANAK',
            'KAB. SAMBAS',
            'KAB. SANGGAU',
            'KAB. SEKADAU',
            'KAB. SINTANG',
            'PONTIANAK',
            'SINGKAWANG',
            'KAB. BALANGAN',
            'KAB. BANJAR',
            'KAB. BARITO KUALA',
            'KAB. HULU SUNGAI SELATAN',
            'KAB. HULU SUNGAI TENGAH',
            'KAB. HULU SUNGAI UTARA',
            'KAB. KOTABARU',
            'KAB. TABALONG',
            'KAB. TANAH BUMBU',
            'KAB. TANAH LAUT',
            'KAB. TAPIN',
            'BANJARBARU',
            'BANJARMASIN',
            'KAB. BARITO SELATAN',
            'KAB. BARITO TIMUR',
            'KAB. BARITO UTARA',
            'KAB. GUNUNG MAS',
            'KAB. KAPUAS',
            'KAB. KATINGAN',
            'KAB. KOTAWARINGIN BARAT',
            'KAB. KOTAWARINGIN TIMUR',
            'KAB. LAMANDAU',
            'KAB. MURUNG RAYA',
            'KAB. PULANG PISAU',
            'KAB. SUKAMARA',
            'KAB. SERUYAN',
            'PALANGKA RAYA',
            'KAB. BERAU',
            'KAB. KUTAI BARAT',
            'KAB. KUTAI KARTANEGARA',
            'KAB. KUTAI TIMUR',
            'KAB. MAHAKAM ULU',
            'KAB. PASER',
            'KAB. PENAJAM PASER UTARA',
            'BALIKPAPAN',
            'BONTANG',
            'SAMARINDA',
            'KAB. BULUNGAN',
            'KAB. MALINAU',
            'KAB. NUNUKAN',
            'KAB. TANA TIDUNG',
            'TARAKAN',
            'KAB. BINTAN',
            'KAB. KARIMUN',
            'KAB. KEPULAUAN ANAMBAS',
            'KAB. LINGGA',
            'KAB. NATUNA',
            'BATAM',
            'TANJUNG PINANG',
            'KAB. BANGKA',
            'KAB. BANGKA BARAT',
            'KAB. BANGKA SELATAN',
            'KAB. BANGKA TENGAH',
            'KAB. BELITUNG',
            'KAB. BELITUNG TIMUR',
            'PANGKAL PINANG',
            'KAB. BOLAANG MONGONDOW',
            'KAB. BOLAANG MONGONDOW SELATAN',
            'KAB. BOLAANG MONGONDOW TIMUR',
            'KAB. BOLAANG MONGONDOW UTARA',
            'KAB. KEPULAUAN SANGIHE',
            'KAB. KEPULAUAN SIAU TAGULANDANG BIARO',
            'KAB. KEPULAUAN TALAUD',
            'KAB. MINAHASA',
            'KAB. MINAHASA SELATAN',
            'KAB. MINAHASA TENGGARA',
            'KAB. MINAHASA UTARA',
            'BITUNG',
            'KOTAMOBAGU',
            'MANADO',
            'TOMOHON',
            'KAB. AGAM',
            'KAB. DHARMASRAYA',
            'KAB. KEPULAUAN MENTAWAI',
            'KAB. LIMA PULUH KOTA',
            'KAB. PADANG PARIAMAN',
            'KAB. PASAMAN',
            'KAB. PASAMAN BARAT',
            'KAB. PESISIR SELATAN',
            'KAB. SIJUNJUNG',
            'KAB. SOLOK',
            'KAB. SOLOK SELATAN',
            'KAB. TANAH DATAR',
            'BUKITTINGGI',
            'PADANG',
            'PADANG PANJANG',
            'PARIAMAN',
            'PAYAKUMBUH',
            'SAWAHLUNTO',
            'SOLOK',
            'KAB. BANYUASIN',
            'KAB. EMPAT LAWANG',
            'KAB. LAHAT',
            'KAB. MUARA ENIM',
            'KAB. MUSI BANYUASIN',
            'KAB. MUSI RAWAS',
            'KAB. MUSI RAWAS UTARA',
            'KAB. OGAN ILIR',
            'KAB. OGAN KOMERING ILIR',
            'KAB. OGAN KOMERING ULU',
            'KAB. OGAN KOMERING ULU SELATAN',
            'KAB. OGAN KOMERING ULU TIMUR',
            'KAB. PENUKAL ABAB LEMATANG ILIR',
            'KAB. LUBUK LINGGAU',
            'PALEMBANG',
            'PAGAR ALAM',
            'PRABUMULIH',
            'KAB. ASAHAN',
            'KAB. BATU BARA',
            'KAB. DAIRI',
            'KAB. DELI SERDANG',
            'KAB. HUMBANG HASUNDUTAN',
            'KAB. KARO',
            'KAB. LABUHAN BATU',
            'KAB. LABUHAN BATU SELATAN',
            'KAB. LABUHAN BATU UTARA',
            'KAB. LANGKAT',
            'KAB. MANDAILING NATAL',
            'KAB. NIAS',
            'KAB. NIAS BARAT',
            'KAB. NIAS SELATAN',
            'KAB. NIAS UTARA',
            'KAB. PADANG LAWAS',
            'KAB. PADANG LAWAS UTARA',
            'KAB. PAKPAK BHARAT',
            'KAB. SAMOSIR',
            'KAB. SERDANG BEDAGAI',
            'KAB. SIMALUNGUN',
            'KAB. TAPANULI SELATAN',
            'KAB. TAPANULI TENGAH',
            'KAB. TAPANULI UTARA',
            'KAB. TOBA SAMOSIR',
            'BINJAI',
            'GUNUNGSITOLI',
            'MEDAN',
            'PADANG SIDEMPUAN',
            'PEMATANG SIANTAR',
            'SIBOLGA',
            'TANJUNG BALAI',
            'TEBING TINGGI',
            'KAB. BENGKAYANG',
            'KAB. KAPUAS HULU',
            'KAB. KAYONG UTARA',
            'KAB. KETAPANG',
            'KAB. KUBU RAYA',
            'KAB. LANDAK',
            'KAB. MELAWI',
            'KAB. MEMPAWAH',
            'KAB. SAMBAS',
            'KAB. SANGGAU',
            'KAB. SEKADAU',
            'KAB. SINTANG',
            'PONTIANAK',
            'SINGKAWANG',
            'KAB. BALANGAN',
            'KAB. BANJAR',
            'KAB. BARITO KUALA',
            'KAB. HULU SUNGAI SELATAN',
            'KAB. HULU SUNGAI TENGAH',
            'KAB. HULU SUNGAI UTARA',
            'KAB. KOTABARU',
            'KAB. TABALONG',
            'KAB. TANAH BUMBU',
            'KAB. TANAH LAUT',
            'KAB. TAPIN',
            'BANJARBARU',
            'BANJARMASIN',
            'KAB. BARITO SELATAN',
            'KAB. BARITO TIMUR',
            'KAB. BARITO UTARA',
            'KAB. GUNUNG MAS',
            'KAB. KAPUAS',
            'KAB. KATINGAN',
            'KAB. KOTAWARINGIN BARAT',
            'KAB. KOTAWARINGIN TIMUR',
            'KAB. LAMANDAU',
            'KAB. MURUNG RAYA',
            'KAB. PULANG PISAU',
            'KAB. SUKAMARA',
            'KAB. SERUYAN',
            'PALANGKA RAYA',
            'KAB. BERAU',
            'KAB. KUTAI BARAT',
            'KAB. KUTAI KARTANEGARA',
            'KAB. KUTAI TIMUR',
            'KAB. MAHAKAM ULU',
            'KAB. PASER',
            'KAB. PENAJAM PASER UTARA',
            'BALIKPAPAN',
            'BONTANG',
            'SAMARINDA',
            'KAB. BULUNGAN',
            'KAB. MALINAU',
            'KAB. NUNUKAN',
            'KAB. TANA TIDUNG',
            'TARAKAN',
            'KAB. BINTAN',
            'KAB. KARIMUN',
            'KAB. KEPULAUAN ANAMBAS',
            'KAB. LINGGA',
            'KAB. NATUNA',
            'BATAM',
            'TANJUNG PINANG',
        ];
    }
}
